# Generated by Django 2.2.5 on 2019-10-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20191006_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_corporate_corporate', to='master.Corporate'),
        ),
        migrations.AddField(
            model_name='customer',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_customer_corporate', to='master.Corporate'),
        ),
        migrations.AddField(
            model_name='team',
            name='corporate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_team_corporate', to='master.Corporate'),
        ),
    ]
