# Generated by Django 2.2.5 on 2019-10-04 02:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190930_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
