# Generated by Django 2.2.5 on 2019-09-30 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='task_work_results', to='works.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_work_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[(1, '社外'), (2, '社内')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('estimate_price', models.IntegerField()),
                ('estimate_date', models.DateField()),
                ('closed_flg', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_projects', to='master.Customer')),
                ('team', models.ForeignKey(default='不明', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='team_projects', to='master.Team')),
            ],
        ),
    ]
