# Generated by Django 2.2.5 on 2019-10-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('社外', '社外'), ('社内', '社内')], max_length=10),
        ),
    ]
