# Generated by Django 2.2.5 on 2019-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20191006_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatetask',
            name='memo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baseform',
            name='form_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
