# Generated by Django 2.2.5 on 2019-10-08 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20191006_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatepurchase',
            old_name='description',
            new_name='memo',
        ),
    ]
