# Generated by Django 2.2.5 on 2019-10-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20191008_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatepurchase',
            name='amount',
        ),
    ]
