# Generated by Django 2.2.5 on 2019-10-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_estimatepurchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatepurchase',
            name='estimate_price',
            field=models.IntegerField(default=0),
        ),
    ]
