# Generated by Django 2.2.5 on 2019-10-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_estimatepurchase_estimate_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatepurchase',
            old_name='price',
            new_name='purchase_price',
        ),
    ]
