# Generated by Django 2.2.5 on 2019-10-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_estimatetask_estimate_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatepurchase',
            options={'ordering': ['estimate', 'row_num']},
        ),
        migrations.AlterModelOptions(
            name='estimatetask',
            options={'ordering': ['estimate', 'row_num']},
        ),
        migrations.AddField(
            model_name='estimatepurchase',
            name='row_num',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimatetask',
            name='row_num',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
