# Generated by Django 2.2.5 on 2019-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20191008_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatepurchase',
            name='estimate_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estimatepurchase',
            name='purchase_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estimatepurchase',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estimatetask',
            name='estimate_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='estimatetask',
            name='time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
